replicaCount: 1

runtime: RUN_TIME

image:
  repository: CI_REGISTRY_IMAGE
  tag: "CI_COMMIT_REF_SLUG"
  pullPolicy: Always

port:
  name: http
  containerPort: 80
  protocol: TCP

service:
  type: ClusterIP
  port: 80

healthcheck:
  enabled: true
  path: /

imagePullSecrets: [ name: gitlab-registry ]

variables:
  enabled: false
  data: DOCKER_VARIABLES
  path: /server/variables.docker.rb
  subpath: variables.docker.rb

istio:
  enabled: true
  secretName: URL
  commonName: URL
  issuerRefName: letsencrypt-prod
  hosts:
    - URL

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  env: dev
